# Generated by Django 5.2.6 on 2025-09-25 17:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        help_text="Source of the transaction, e.g., mpesa, bank",
                        max_length=50,
                    ),
                ),
                (
                    "provider_txn_id",
                    models.CharField(
                        help_text="ID from provider", max_length=100, unique=True
                    ),
                ),
                ("sender", models.CharField(max_length=100)),
                ("receiver", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="KES", max_length=10)),
                (
                    "timestamp",
                    models.DateTimeField(help_text="Timestamp from provider"),
                ),
                (
                    "processed",
                    models.BooleanField(
                        default=False, help_text="Has fraud detection been applied?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
