import uuid
from django.db import models
from transactions.models import Transaction


class FraudAlert(models.Model):
    """
    Stores fraud alerts linked to a transaction.
    Each alert is generated by a rule in the fraud detection engine.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    transaction = models.ForeignKey(Transaction, on_delete=models.CASCADE, related_name="alerts")
    rule = models.CharField(max_length=100, help_text="Which rule triggered this alert?")
    reason = models.TextField(help_text="Human-readable explanation")
    severity = models.PositiveSmallIntegerField(default=1, help_text="1=low, 5=critical")
    resolved = models.BooleanField(default=False)

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"Alert for {self.transaction.id} - {self.rule}"
